name: HDX nightly refresh

on:
  workflow_dispatch:
  schedule:
    - cron: '27 3 * * *'      # 03:27 UTC daily

jobs:
  refresh:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/pathfinder

    services:
      db:
        image: postgis/postgis:16-3.4
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: pathfinder
        ports: ['5432:5432']
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 5s --health-timeout 5s --health-retries 12

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Python deps
        run: pip install -r requirements.txt

      # ── apply schema using the same SQLAlchemy URL the loader will use
      - name: Initialize staging + clean tables
        run: |
          python - <<'PY'
          import os, pathlib, sqlalchemy
          engine = sqlalchemy.create_engine(os.environ["DATABASE_URL"])
          sql    = pathlib.Path("sql/02_staging_clean.sql").read_text()
          with engine.begin() as conn:
              conn.exec_driver_sql(sql)
          print("✅  schema applied")
          PY

      - name: Fetch newest HDX workbook
        run: bash scripts/fetch_hdx_pv.sh

      - name: Run ETL loader
        run: python scratch/load_pv_monthly.py
