name: HDX nightly refresh

on:
  workflow_dispatch:              # manual trigger
  schedule:
    - cron: '27 3 * * *'          # 03 :27 UTC every day

jobs:
  refresh:
    runs-on: ubuntu-latest

    # All steps inherit this -> loader connects to localhost
    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/pathfinder

    services:
      db:
        image: postgis/postgis:16-3.4
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: pathfinder
        ports: ['5432:5432']
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # ── NEW: psql client so we can run the DDL
      - name: Install system psql client
        run: sudo apt-get update && sudo apt-get -y install postgresql-client

      # ── NEW: apply schema (creates acled_monthly_staging & clean)
      - name: Initialize schema (staging + clean)
        env:
          PGPASSWORD: postgres
        run: |
          psql -h localhost -U postgres -d pathfinder -f sql/02_staging_clean.sql

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Fetch newest HDX workbook
        run: bash scripts/fetch_hdx_pv.sh

      - name: Run ETL loader
        run: python scratch/load_pv_monthly.py
