name: HDX nightly refresh

on:
  workflow_dispatch:            # manual trigger button
  schedule:
    - cron: '27 3 * * *'        # 03:27 UTC every day

jobs:
  refresh:
    runs-on: ubuntu-latest

    # Connection string the loader will read
    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/pathfinder

    services:
      db:
        image: postgis/postgis:16-3.4
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: pathfinder
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Bootstrap roads schema
        run: python scripts/bootstrap_roads.py

      - name: Fetch newest HDX workbook
        run: bash scripts/fetch_hdx_pv.sh

      - name: Run ETL loader
        run: python scratch/load_pv_monthly.py
